POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username":"adsmin",
  "password":"admin"
}

###
POST http://localhost:3001/api/posts
Content-Type: application/json

{
  "title":"Post 2",
  "description":"Day la bai post so 2"
}

###
GET http://localhost:3001/api/posts
